spring.application.name=universidad

server.port=8086

# SQL Server
app.sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=universidad_db;encrypt=false;trustServerCertificate=true
app.sqlserver.username=sa
app.sqlserver.password=Admin12345
app.sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# PostgreSQL
app.postgres.url=jdbc:postgresql://localhost:5432/universidad_db
app.postgres.username=postgres
app.postgres.password=postgres
app.postgres.driver=org.postgresql.Driver


